### PR TITLE
Instructions updated

### PR DESCRIPTION
**Pull request by tbnv**
I updated the setup instructions (mostly) because it looks like it was not clear for everyone. Plus, drag'n'drop of the plugin on the app icon doesn't seem to place it at the right place.

### CODE REVIEW

**Comment by C4MS** [comment]
I think you might highlight that is required to enable scripting on the preferences panel
This option comes disabled by default I believe...

**Comment by FredericJacobs** [comment]
@C4MS : Yep. Indeed. Why do you still use it?
I believe it's no more needed.

**Comment by C4MS** [comment]
@FredericJacobs Im new to Sketch and for some reason the margin is still visible, so I gave it a try

**Comment by FredericJacobs** [comment]
Are you running the latest version?

**Comment by C4MS** [comment]
Yup the lastest free version

**Comment by FredericJacobs** [comment]
The Mac App Store version is working perfectly without this btw

**Pull request closed without merging**
